name: Тесты на Pull Request

on: pull_request

env:
    REGISTRY: ghcr.io
    IMAGE_NAME: ${{ github.repository }}

jobs:
    test:
        name: Проверяем стили
        runs-on: ubuntu-latest
        steps:
            - name: Checkout repository
              uses: actions/checkout@v4

            - uses: pnpm/action-setup@v2
              with:
                  version: 7.26.3

            - uses: actions/setup-node@v3
              with:
                  node-version: '18'
                  cache: 'pnpm'

            - name: Install
              run: |
                pnpm config set auto-install-peers true
                pnpm install

            - name: Check
              run: pnpm lint && pnpm stylelint

    test-format:
        name: Выполняем тесты
        runs-on: ubuntu-latest
        steps:
            - name: Checkout repository
              uses: actions/checkout@v4

            - uses: pnpm/action-setup@v2
              with:
                  version: 7.26.3

            - uses: actions/setup-node@v3
              with:
                  node-version: '18'
                  cache: 'pnpm'

            - name: Install
              run: |
                pnpm config set auto-install-peers true
                pnpm install

            - name: Check
              run: pnpm test
